version: "3.8"
services:
  prefect-flows:
    container_name: flows
    depends_on:
      - mlflow
    build:
      context: ./flows
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./data/.prefect:/root/.prefect
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
      PREFECT_API_KEY: ${PREFECT_API_KEY}
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --backend-store-uri sqlite:///database.db --default-artifact-root /mlruns --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./database:/database

  fastapi-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./model:/app/model
    ports:
      - "8000:8000"
    environment:
      SERVER_API_KEY: ${SERVER_API_KEY}

  streamlit-app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8501:8501"
    environment:
      SERVER_API_URL: ${SERVER_API_URL}
      SERVER_API_KEY: ${SERVER_API_KEY}
    depends_on:
      - fastapi-server
